W-10688508: Copy overwrite logic
mulesoft/mule-file-connector pull request #192
Opened 2022-05-20 18:14 UTC by GuidoGianfrate

2022-05-20 20:53 UTC, giss-ignacio requested changes
Can we add tests for the cases this will work now?
And the work item number (gus). In the next commits and branch name. 
thanks

2022-05-23 13:40 UTC, acurci-at-mulesoft commented
Could you add the GUS number to the PR title?

2022-05-23 14:34 UTC, GuidoGianfrate commented
@giss-ignacio There are not way to reproduce the issue that we are trying to solve with this change
@acurci-at-mulesoft Gus work id added to the pull request name

2022-05-24 13:24 UTC, giss-ignacio approved these changes

2022-05-24 16:07 UTC, merged