Chore/w 11210231
mulesoft/mule-file-connector pull request #196
Opened 2022-06-09 17:58 UTC by francisco-nery

2022-06-13 18:02 UTC, konangc87 requested changes

2022-06-13 18:02 UTC, konangc87 commented on src/main/java/org/mule/extension/file/internal/command/LocalListCommand.java
> +      offset = 1;
what happen if offset is set to 1 externally? would return the same subset than setting it to 0?

2022-06-13 20:15 UTC, francisco-nery commented on src/main/java/org/mule/extension/file/api/subset/SizeComparator.java
> +    long size1 = o1.getAttributes().get().getSize();
No since size is a long and casting to int would overflow. Changed to Long.compare

2022-06-14 12:28 UTC, konangc87 reviewed
LGTM

2022-06-14 12:28 UTC, konangc87 submitted a review, later dismissed

2022-06-16 18:10 UTC, konangc87 approved these changes

2022-06-16 21:46 UTC, konangc87 submitted a review, later dismissed

2022-06-22 20:08 UTC, acurci-at-mulesoft requested changes

2022-06-29 21:02 UTC, acurci-at-mulesoft requested changes

2022-06-30 00:03 UTC, acurci-at-mulesoft requested changes

2022-06-30 20:05 UTC, merged